# This file was generated by Psc-Package2Nix
# You will not want to edit this file.
# To change the contents of this file, first fork Psc-Package2Nix
# And edit the $file_template

{ pkgs ? import <nixpkgs> {} }:

let
  inputs = {

    "aff" = pkgs.stdenv.mkDerivation {
      name = "aff";
      version = "v5.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-aff.git";
        rev = "v5.1.0";
        sha256 = "00s97s7awa8n7h2p6hkc8kpmlwfvigbbj1phvwx3a90whczfi99d";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "aff-promise" = pkgs.stdenv.mkDerivation {
      name = "aff-promise";
      version = "v2.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/nwolverson/purescript-aff-promise.git";
        rev = "v2.0.1";
        sha256 = "1zy91qhd0zfxys4bk5ncvvfad6hqpa2ghd4xn8vqp4zj0xr8phwc";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "arraybuffer-types" = pkgs.stdenv.mkDerivation {
      name = "arraybuffer-types";
      version = "v2.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-arraybuffer-types.git";
        rev = "v2.0.0";
        sha256 = "059a8n49yhl46l1b1j2qj4ichzq6dzj29ajkfvw88npzj5w2rshy";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "arrays" = pkgs.stdenv.mkDerivation {
      name = "arrays";
      version = "v5.2.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-arrays.git";
        rev = "v5.2.0";
        sha256 = "1niqvccjg3kaix8rcpjsvh31j4hf6myiahmbz3my7wjbvx5hcjgc";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "avar" = pkgs.stdenv.mkDerivation {
      name = "avar";
      version = "v3.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-avar.git";
        rev = "v3.0.0";
        sha256 = "14g05jm2xricy5b9vn4k4lhc9lzi5jvpvv85h10s17kn4wwi9igk";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "bifunctors" = pkgs.stdenv.mkDerivation {
      name = "bifunctors";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-bifunctors.git";
        rev = "v4.0.0";
        sha256 = "1bdra5fbkraglqrrm484vw8h0wwk48kzkn586v4y7fg106q1q386";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "catenable-lists" = pkgs.stdenv.mkDerivation {
      name = "catenable-lists";
      version = "v5.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-catenable-lists.git";
        rev = "v5.0.1";
        sha256 = "0mbpb8xr9a7a4bvawhki7js5cbv7c0lv0vdwb6r8nmv6b61gzg27";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "choco-pie" = pkgs.stdenv.mkDerivation {
      name = "choco-pie";
      version = "v3.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/justinwoo/purescript-chocopie.git";
        rev = "v3.0.0";
        sha256 = "19a7g4ihq56rn4wyq6zln0qacd5aiwhdx8y8nhs0s7fn11vh3bpf";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "colors" = pkgs.stdenv.mkDerivation {
      name = "colors";
      version = "v5.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/sharkdp/purescript-colors.git";
        rev = "v5.0.0";
        sha256 = "05bkfqllfpkh7nj0nzgd5p387hlpk0x35nam1i6xm3vzma9csj18";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "console" = pkgs.stdenv.mkDerivation {
      name = "console";
      version = "v4.2.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-console.git";
        rev = "v4.2.0";
        sha256 = "1b2nykdq1dzaqyra5pi8cvvz4dsbbkg57a2c88yi931ynm19nnw6";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "const" = pkgs.stdenv.mkDerivation {
      name = "const";
      version = "v4.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-const.git";
        rev = "v4.1.0";
        sha256 = "0qbd2aisax52yw6sybdhs7na943cbsd6mylhhgsamrf7hzh6v51p";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "contravariant" = pkgs.stdenv.mkDerivation {
      name = "contravariant";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-contravariant.git";
        rev = "v4.0.0";
        sha256 = "0vvcgfclx236kg4y76nwih787wyqacq8mmx42q64xzl964yrwxkk";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "control" = pkgs.stdenv.mkDerivation {
      name = "control";
      version = "v4.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-control.git";
        rev = "v4.1.0";
        sha256 = "10703zvsnjm5fc74k6wzjsvpsfyc3jci3jxhm7rxf7ymya9z1z53";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "coroutines" = pkgs.stdenv.mkDerivation {
      name = "coroutines";
      version = "v5.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-coroutines.git";
        rev = "v5.0.0";
        sha256 = "1jax7by8kn9fjg00avhziy3n18i3510iwzs3d73ziplanbw4qw4k";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "css" = pkgs.stdenv.mkDerivation {
      name = "css";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-css.git";
        rev = "v4.0.0";
        sha256 = "0f6gib6rp20qz08vramw7k6kv2ck315lmshjpii8zmkjb5ya0w55";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "datetime" = pkgs.stdenv.mkDerivation {
      name = "datetime";
      version = "v4.1.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-datetime.git";
        rev = "v4.1.1";
        sha256 = "06ghfvbvd5sd0q014qi8j8glk2g2j9f8z8cwq2318kllp92gz07q";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "debug" = pkgs.stdenv.mkDerivation {
      name = "debug";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/garyb/purescript-debug.git";
        rev = "v4.0.0";
        sha256 = "0gwjj80akys0h111i74n429fmny992gx0r4rk1n98gqlqm5cmi21";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "distributive" = pkgs.stdenv.mkDerivation {
      name = "distributive";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-distributive.git";
        rev = "v4.0.0";
        sha256 = "0zbn0yq1vv7fbbf1lncg80irz0vg7wnw9b9wrzxhdzpbkw4jinsl";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "dom-indexed" = pkgs.stdenv.mkDerivation {
      name = "dom-indexed";
      version = "v7.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-dom-indexed.git";
        rev = "v7.0.0";
        sha256 = "18is75gsiix9w3f3lkly15cvs7ma1qc13hhi6wkl8nsj2g9g55ld";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "effect" = pkgs.stdenv.mkDerivation {
      name = "effect";
      version = "v2.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-effect.git";
        rev = "v2.0.1";
        sha256 = "1vqw5wrdxzh1ww6z7271xr4kg4mx0r3k3mwg18dmgmzj11wbn2wh";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "either" = pkgs.stdenv.mkDerivation {
      name = "either";
      version = "v4.1.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-either.git";
        rev = "v4.1.1";
        sha256 = "12j7vvjly0bgxidxmb2pflx0zy7x425dnvxk2y1pm66n0hbsq7ns";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "enums" = pkgs.stdenv.mkDerivation {
      name = "enums";
      version = "v4.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-enums.git";
        rev = "v4.0.1";
        sha256 = "0qq0pgmq497nfml0y8xb2qdpga5xqp9sqq4ilv1rpyhg1v7nzb6v";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "event" = pkgs.stdenv.mkDerivation {
      name = "event";
      version = "v1.2.4";
      src = pkgs.fetchgit {
        url = "https://github.com/paf31/purescript-event.git";
        rev = "v1.2.4";
        sha256 = "0zzlg4ggzv9s2ipg84wj4qbdib3qn38zdzpr8brv79kvb3f0lnzz";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "exceptions" = pkgs.stdenv.mkDerivation {
      name = "exceptions";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-exceptions.git";
        rev = "v4.0.0";
        sha256 = "17s0rg9k4phivhx9j3l2vqqfdhk61gpj1xfqy8w6zj3rnxj0b2cv";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "exists" = pkgs.stdenv.mkDerivation {
      name = "exists";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-exists.git";
        rev = "v4.0.0";
        sha256 = "0bbdbw3jaqyi8dj2d52zvfgx4vl84d8cr6hp43vy8lfjfcbj0wlk";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "filterable" = pkgs.stdenv.mkDerivation {
      name = "filterable";
      version = "v3.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/LiamGoodacre/purescript-filterable.git";
        rev = "v3.0.1";
        sha256 = "1sj0r49pzkiibrin28p2ikh3z0884kzqa9p6glzh5hxh6smx8ihb";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "foldable-traversable" = pkgs.stdenv.mkDerivation {
      name = "foldable-traversable";
      version = "v4.1.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-foldable-traversable.git";
        rev = "v4.1.1";
        sha256 = "03x89xcmphckzjlp4chc7swrpw347ll5bvr2yp7x9v2jqw2jlyi1";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "foreign" = pkgs.stdenv.mkDerivation {
      name = "foreign";
      version = "v5.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-foreign.git";
        rev = "v5.0.0";
        sha256 = "15mz2s4f8crkd721z4df2aag4s0wil6fs07cpcmi7dpnkn7a4nab";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "foreign-object" = pkgs.stdenv.mkDerivation {
      name = "foreign-object";
      version = "v2.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-foreign-object.git";
        rev = "v2.0.0";
        sha256 = "0nhxdjfb78gxsp13jpkb2dcpv22hicviclcr61ijrahh69fyncv7";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "fork" = pkgs.stdenv.mkDerivation {
      name = "fork";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-fork.git";
        rev = "v4.0.0";
        sha256 = "1jygqzyci40c28gw2ygnx8v52hilhajj1bdpn7ndvss4i7yh1lcp";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "free" = pkgs.stdenv.mkDerivation {
      name = "free";
      version = "v5.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-free.git";
        rev = "v5.1.0";
        sha256 = "0f093s5wvbip547fyfxyjqn60z5ay11hs9vzw1h480307vpzq3wm";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "freeap" = pkgs.stdenv.mkDerivation {
      name = "freeap";
      version = "v5.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/ethul/purescript-freeap.git";
        rev = "v5.0.1";
        sha256 = "007840vpxa4gz0fvjbahyky2xzz625gzfaiy2wjpb50d9qacsr7y";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "freet" = pkgs.stdenv.mkDerivation {
      name = "freet";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-freet.git";
        rev = "v4.0.0";
        sha256 = "1kpgggwimxjvdvhn6s7z4lzg3yw1rqg5f7pyamx9gh232s4va40i";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "functions" = pkgs.stdenv.mkDerivation {
      name = "functions";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-functions.git";
        rev = "v4.0.0";
        sha256 = "0675k5kxxwdvsjs6a3is8pwm3hmv0vbcza1b8ls10gymmfz3k3hj";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "functors" = pkgs.stdenv.mkDerivation {
      name = "functors";
      version = "v3.1.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-functors.git";
        rev = "v3.1.1";
        sha256 = "1cnn3zhk6qcyiwbbpvrdqgsbch4qihx2y9d6sv45bvd8kzrbd306";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "gen" = pkgs.stdenv.mkDerivation {
      name = "gen";
      version = "v2.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-gen.git";
        rev = "v2.1.0";
        sha256 = "0ddsfb6a23rahkw9d3ymp2sf6d6vxndj73y61cdv74zrlr2nx74p";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "generics-rep" = pkgs.stdenv.mkDerivation {
      name = "generics-rep";
      version = "v6.1.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-generics-rep.git";
        rev = "v6.1.1";
        sha256 = "15vchzbcvf6byks90q14lvcwb8hnxqzm2mrlxi7v1f7has4s74kn";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "globals" = pkgs.stdenv.mkDerivation {
      name = "globals";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-globals.git";
        rev = "v4.0.0";
        sha256 = "150mc0kv0cb5fkx0szicwczjr54bglmlyaynj2grf1r4gnjg967s";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "gomtang-basic" = pkgs.stdenv.mkDerivation {
      name = "gomtang-basic";
      version = "v0.2.0";
      src = pkgs.fetchgit {
        url = "https://github.com/justinwoo/purescript-gomtang-basic.git";
        rev = "v0.2.0";
        sha256 = "11zp6id0hrq9hmr0w395ldf403p6v6ldz0miisrxmdmpcrcm3j54";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "halogen" = pkgs.stdenv.mkDerivation {
      name = "halogen";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-halogen.git";
        rev = "v4.0.0";
        sha256 = "13q1fj33wmqa8bhxp0k6cc7v218b0xnx8rnh4p3ci637x3via3bh";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "halogen-css" = pkgs.stdenv.mkDerivation {
      name = "halogen-css";
      version = "v8.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-halogen-css.git";
        rev = "v8.0.0";
        sha256 = "1a8sj8ydfnvj3vh2l3f0yyd69y7v4qki1a5m99n0v2aqc1y6nrzl";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "halogen-vdom" = pkgs.stdenv.mkDerivation {
      name = "halogen-vdom";
      version = "v3.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-halogen-vdom.git";
        rev = "v3.0.0";
        sha256 = "0zs82fymvg1w2ifkj3h3hnq2cpa88lzkbl3i35rp1fccn5f70bpi";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "identity" = pkgs.stdenv.mkDerivation {
      name = "identity";
      version = "v4.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-identity.git";
        rev = "v4.1.0";
        sha256 = "1scdgbfkphfmapw7p9rnsiynpmqzyvnal2glzj450q51f8g1dhld";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "integers" = pkgs.stdenv.mkDerivation {
      name = "integers";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-integers.git";
        rev = "v4.0.0";
        sha256 = "17d4bfpnrmbxlc7hhhrvnli70ydaqyr26zgvc9q52a76zgdcb4cf";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "invariant" = pkgs.stdenv.mkDerivation {
      name = "invariant";
      version = "v4.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-invariant.git";
        rev = "v4.1.0";
        sha256 = "1fimpbh3yb7clvqxcdf4yf9im64z0v2s9pbspfacgq5b4vshjas9";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "jajanmen" = pkgs.stdenv.mkDerivation {
      name = "jajanmen";
      version = "v0.2.0";
      src = pkgs.fetchgit {
        url = "https://github.com/justinwoo/purescript-jajanmen.git";
        rev = "v0.2.0";
        sha256 = "1pd0aij1h9y0i3pzz8x8liv80fxlm27yiybrs93xqh275a706km3";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "js-date" = pkgs.stdenv.mkDerivation {
      name = "js-date";
      version = "v6.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-js-date.git";
        rev = "v6.0.0";
        sha256 = "19qyzbr4a1ca8znbd8gcbz0a801f5p1v238ky3408gdx4ba32zjd";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "js-timers" = pkgs.stdenv.mkDerivation {
      name = "js-timers";
      version = "v4.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-js-timers.git";
        rev = "v4.0.1";
        sha256 = "1a8092sli7zqw1wflibhjza1ww21dxl7x7r602iazzwh2g70v4dg";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "lazy" = pkgs.stdenv.mkDerivation {
      name = "lazy";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-lazy.git";
        rev = "v4.0.0";
        sha256 = "156q89l4nvvn14imbhp6xvvm82q7kqh1pyndmldmnkhiqyr84vqv";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "lcg" = pkgs.stdenv.mkDerivation {
      name = "lcg";
      version = "v2.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-lcg.git";
        rev = "v2.0.0";
        sha256 = "1851cq2g84jzjbvbmncbivbhaqzj9zv5ni3gs14k04nmx2brxmvj";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "lenient-html-parser" = pkgs.stdenv.mkDerivation {
      name = "lenient-html-parser";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/justinwoo/purescript-lenient-html-parser.git";
        rev = "v4.0.0";
        sha256 = "19i4vcj93nz400yiyl4rj190alp5yv9lxm4vw83a5nrk32pll5xi";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "lists" = pkgs.stdenv.mkDerivation {
      name = "lists";
      version = "v5.4.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-lists.git";
        rev = "v5.4.0";
        sha256 = "044qr0812wh6a5vz2snm5rrpav3jnykp75acri56qxih1gd3rqla";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "makkori" = pkgs.stdenv.mkDerivation {
      name = "makkori";
      version = "v1.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/justinwoo/purescript-makkori.git";
        rev = "v1.0.0";
        sha256 = "09i5j2xqp6rjmljc6kbn3h1ybw1j3dfwdl6bxzr0wqk3y14wpdlq";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "math" = pkgs.stdenv.mkDerivation {
      name = "math";
      version = "v2.1.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-math.git";
        rev = "v2.1.1";
        sha256 = "1msmy9w7y6fij62sdc55w68gpwkhm6lhgc8qjisjk4sxx1wdg1rr";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "maybe" = pkgs.stdenv.mkDerivation {
      name = "maybe";
      version = "v4.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-maybe.git";
        rev = "v4.0.1";
        sha256 = "073wa0d51daxdwacfcxg5pf6ch63n4ii55xm1ih87bxrg8mp52mx";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "media-types" = pkgs.stdenv.mkDerivation {
      name = "media-types";
      version = "v4.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-media-types.git";
        rev = "v4.0.1";
        sha256 = "0ykwmxrhmwfy6c5mxjxa43xdf5xqakrqyvr5fn986yad50gjqj75";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "milkis" = pkgs.stdenv.mkDerivation {
      name = "milkis";
      version = "v6.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/justinwoo/purescript-milkis.git";
        rev = "v6.1.0";
        sha256 = "15gpyzxh4njd9l5isqajrwrz4rk21d2pw5b06jrhcj9d4dsac5xh";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "naporitan" = pkgs.stdenv.mkDerivation {
      name = "naporitan";
      version = "v0.2.0";
      src = pkgs.fetchgit {
        url = "https://github.com/justinwoo/purescript-naporitan.git";
        rev = "v0.2.0";
        sha256 = "0g9aav1bzrkda6zv8d77hy5gf0jjm7x026rfbbqsrm6flfi8k85n";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "newtype" = pkgs.stdenv.mkDerivation {
      name = "newtype";
      version = "v3.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-newtype.git";
        rev = "v3.0.0";
        sha256 = "0qvk9p41miy806b05b4ikbr3if0fcyc35gfrwd2mflcxxp46011c";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "node-buffer" = pkgs.stdenv.mkDerivation {
      name = "node-buffer";
      version = "v5.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-node/purescript-node-buffer.git";
        rev = "v5.0.0";
        sha256 = "0ih2y29srdxgn526fw2v1y95hpivjil44vkl93w6nrqsymki36y0";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "node-child-process" = pkgs.stdenv.mkDerivation {
      name = "node-child-process";
      version = "v5.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-node/purescript-node-child-process.git";
        rev = "v5.0.0";
        sha256 = "0igspvgsqabwrgync4znn7gg89xl4lck9hdqfscawj8fj7rg960d";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "node-fs" = pkgs.stdenv.mkDerivation {
      name = "node-fs";
      version = "v5.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-node/purescript-node-fs.git";
        rev = "v5.0.0";
        sha256 = "1hkg8j4zkyq71g2bn3vpfqb8x49rdd9k0ayv3zf6l8k80gp3qigx";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "node-fs-aff" = pkgs.stdenv.mkDerivation {
      name = "node-fs-aff";
      version = "v6.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-node/purescript-node-fs-aff.git";
        rev = "v6.0.0";
        sha256 = "0vjc9zag7y20yxhhv45hrwv9fbpmp0szv40vaxl5x8mnd5wv28x7";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "node-http" = pkgs.stdenv.mkDerivation {
      name = "node-http";
      version = "v5.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-node/purescript-node-http.git";
        rev = "v5.0.0";
        sha256 = "1pwh3alx32gcih2w050pac4yy9l4q6zxar8i7yri3j23nfg6lcpi";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "node-path" = pkgs.stdenv.mkDerivation {
      name = "node-path";
      version = "v3.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-node/purescript-node-path.git";
        rev = "v3.0.0";
        sha256 = "0j1ni52m62dpcrfakl1ik131i31bkg91yv0p1c40sdw0f59fzf6x";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "node-process" = pkgs.stdenv.mkDerivation {
      name = "node-process";
      version = "v6.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-node/purescript-node-process.git";
        rev = "v6.0.0";
        sha256 = "19p4ylxn9cfa7drxrl4gzsfp52jwgm67n5k7rs9lazkp1lvmk0jh";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "node-sqlite3" = pkgs.stdenv.mkDerivation {
      name = "node-sqlite3";
      version = "v6.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/justinwoo/purescript-node-sqlite3.git";
        rev = "v6.0.0";
        sha256 = "0xrby3w76i7ig26jgfvr8lmiih0rkj2d3rbzm5d7x476444n7l56";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "node-streams" = pkgs.stdenv.mkDerivation {
      name = "node-streams";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-node/purescript-node-streams.git";
        rev = "v4.0.0";
        sha256 = "098wdq0rj4nkc470fwmiaars7vxac9n1dh4d82jrji3m77n473da";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "node-url" = pkgs.stdenv.mkDerivation {
      name = "node-url";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-node/purescript-node-url.git";
        rev = "v4.0.0";
        sha256 = "0qbpdz62psy7hb34hw5rw2x1pq7yhd214ysza0xh46c3nlp0ib9y";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "nonempty" = pkgs.stdenv.mkDerivation {
      name = "nonempty";
      version = "v5.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-nonempty.git";
        rev = "v5.0.0";
        sha256 = "1vz174sg32cqrp52nwb2vz9frrzmdwzzlgl4vc2cm5wlf2anirxj";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "now" = pkgs.stdenv.mkDerivation {
      name = "now";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-now.git";
        rev = "v4.0.0";
        sha256 = "18h5pif2dy4r7w1xg2zw4mvdqlar9xqp3rawkiavmsc946ncf3zs";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "nullable" = pkgs.stdenv.mkDerivation {
      name = "nullable";
      version = "v4.1.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-nullable.git";
        rev = "v4.1.1";
        sha256 = "14qaxxga8gqlr4pijyvqycdyhjr6qpz3h4aarficw5j75b7x8nyv";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "numbers" = pkgs.stdenv.mkDerivation {
      name = "numbers";
      version = "v6.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/sharkdp/purescript-numbers.git";
        rev = "v6.0.0";
        sha256 = "1kzdg69llbmrccmgwrpfiq6hr6jdg2zl40qgzj10nzbhgqrbv2y1";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "options" = pkgs.stdenv.mkDerivation {
      name = "options";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-options.git";
        rev = "v4.0.0";
        sha256 = "1yfsx3fxwqkcb7q6kifbsrx8wnr8j6gg5nm3ybgiwkbdk6s1j7v2";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "ordered-collections" = pkgs.stdenv.mkDerivation {
      name = "ordered-collections";
      version = "v1.6.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-ordered-collections.git";
        rev = "v1.6.0";
        sha256 = "1drifyf25g8nclzmq40npm25av8slrr4l4lvlz9f0j07r893ir61";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "orders" = pkgs.stdenv.mkDerivation {
      name = "orders";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-orders.git";
        rev = "v4.0.0";
        sha256 = "13p1sm4dxkmxhld9x5qqg62iiajjb3qpzs66c1r24y5fs4zsfry4";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "parallel" = pkgs.stdenv.mkDerivation {
      name = "parallel";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-parallel.git";
        rev = "v4.0.0";
        sha256 = "1d5bnagabw2k8yxywkygwrpblb2ggqh2fhpqfrx2sj1y53x332hg";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "partial" = pkgs.stdenv.mkDerivation {
      name = "partial";
      version = "v2.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-partial.git";
        rev = "v2.0.0";
        sha256 = "0nw5989ydin2d12b97ch4pdynxkq91xpj7yym5gpd5fpbgy36mdi";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "posix-types" = pkgs.stdenv.mkDerivation {
      name = "posix-types";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-node/purescript-posix-types.git";
        rev = "v4.0.0";
        sha256 = "0xvxjvxr7n4dv53p8w5qfmgx37cga5bp2rjhkbfvj89rb74vm3i1";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "prelude" = pkgs.stdenv.mkDerivation {
      name = "prelude";
      version = "v4.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-prelude.git";
        rev = "v4.1.0";
        sha256 = "1pwqhsba4xyywfflma5rfqzqac1vmybwq7p3wkm4wsackvbn34h5";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "prettier" = pkgs.stdenv.mkDerivation {
      name = "prettier";
      version = "v0.2.0";
      src = pkgs.fetchgit {
        url = "https://github.com/gcanti/purescript-prettier.git";
        rev = "v0.2.0";
        sha256 = "17fkkdiiwd4ydqg606ragawxlf8kkl9nnizpsciginzw85jzpy5s";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "profunctor" = pkgs.stdenv.mkDerivation {
      name = "profunctor";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-profunctor.git";
        rev = "v4.0.0";
        sha256 = "1v4kvmhmiwznd4lswp9339h64pgv5zvd3vm1q7gzj70767a3941i";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "profunctor-lenses" = pkgs.stdenv.mkDerivation {
      name = "profunctor-lenses";
      version = "v6.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-profunctor-lenses.git";
        rev = "v6.0.0";
        sha256 = "10f2mil63m7wmbjy73bpc3vazkv552vkndpzvjpm2axh5wymnlc8";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "proxy" = pkgs.stdenv.mkDerivation {
      name = "proxy";
      version = "v3.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-proxy.git";
        rev = "v3.0.0";
        sha256 = "0rqf25b1n9p5sgx7gdsxwrfv9rb3sqxgqmqpp5kdm30lfk7snz24";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "quickcheck" = pkgs.stdenv.mkDerivation {
      name = "quickcheck";
      version = "v6.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-quickcheck.git";
        rev = "v6.0.0";
        sha256 = "09s8j587ccwdjr65y6fkh8k0v8bvih2gn67qdy14qb2f3vqrcm26";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "random" = pkgs.stdenv.mkDerivation {
      name = "random";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-random.git";
        rev = "v4.0.0";
        sha256 = "0k37v7z529adx6ypxj0xjyfrz45qia6p0vki2wpvi8lik7c698gf";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "record" = pkgs.stdenv.mkDerivation {
      name = "record";
      version = "v2.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-record.git";
        rev = "v2.0.0";
        sha256 = "1hf6y3bjz3hs16xr50a0pj6p4akw11nw7gpn74vjisjrpga3r1gz";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "record-format" = pkgs.stdenv.mkDerivation {
      name = "record-format";
      version = "v0.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/kcsongor/purescript-record-format.git";
        rev = "v0.1.0";
        sha256 = "1bw00l68azyad6b33iqhfjmm0n1j58h1ljli9772ybwhh8slsh5h";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "refs" = pkgs.stdenv.mkDerivation {
      name = "refs";
      version = "v4.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-refs.git";
        rev = "v4.1.0";
        sha256 = "08161iy1xbafzblv033v84156azpcqkiw9v9d6gliphrq5fm17gm";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "shoronpo" = pkgs.stdenv.mkDerivation {
      name = "shoronpo";
      version = "v0.3.0";
      src = pkgs.fetchgit {
        url = "https://github.com/justinwoo/purescript-shoronpo.git";
        rev = "v0.3.0";
        sha256 = "0vyzs7yzc8dxvci2y6qzbwa82ag8big5qwiffx73fzvk52k5hfy6";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "simple-json" = pkgs.stdenv.mkDerivation {
      name = "simple-json";
      version = "v4.4.1";
      src = pkgs.fetchgit {
        url = "https://github.com/justinwoo/purescript-simple-json.git";
        rev = "v4.4.1";
        sha256 = "1p0h29p4xbj2njl9kwyg4a0nqlnagz8cs3l37i4ww7l3b0r6hww6";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "st" = pkgs.stdenv.mkDerivation {
      name = "st";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-st.git";
        rev = "v4.0.0";
        sha256 = "0m2jkb9dmpbr8s1c20l7sm2q11y5rx8gqfiyspnyhq5apzkknjr0";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "string-parsers" = pkgs.stdenv.mkDerivation {
      name = "string-parsers";
      version = "v5.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/paf31/purescript-string-parsers.git";
        rev = "v5.0.0";
        sha256 = "1lykswyd3icv9lx4r096lxfd244i0pzj2f4fpm604czzlfw6bspv";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "strings" = pkgs.stdenv.mkDerivation {
      name = "strings";
      version = "v4.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-strings.git";
        rev = "v4.0.1";
        sha256 = "147l3l3fzn7liparhm2y3p8j4ck1lblra5j493p2hy5yy5ndznc8";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "sunde" = pkgs.stdenv.mkDerivation {
      name = "sunde";
      version = "v1.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/justinwoo/purescript-sunde.git";
        rev = "v1.0.0";
        sha256 = "1s62al6ark10hqc6kdz3nqarblpa6fmdy5kb3bjlxsa8nib436pa";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "tailrec" = pkgs.stdenv.mkDerivation {
      name = "tailrec";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-tailrec.git";
        rev = "v4.0.0";
        sha256 = "0z7k80nl8dgv8mc2w8xsl2n0637bd1l8ppxak8kaifgjjwa81hx3";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "test-unit" = pkgs.stdenv.mkDerivation {
      name = "test-unit";
      version = "v14.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/bodil/purescript-test-unit.git";
        rev = "v14.0.0";
        sha256 = "0iyqdrhb0n5qpck8cprl68034ivywmphbw5wr7zy1jlyj9450nwh";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "these" = pkgs.stdenv.mkDerivation {
      name = "these";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-these.git";
        rev = "v4.0.0";
        sha256 = "0ywwpbcz1d0pdi3f9h9kla52vq1if8zwdz7jq7lqz5s8zj8kyg5r";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "toppokki" = pkgs.stdenv.mkDerivation {
      name = "toppokki";
      version = "v1.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/justinwoo/purescript-toppokki.git";
        rev = "v1.0.0";
        sha256 = "00blhsk7j3xhvp16kj2qlmzd01g1v8nn154gr21l4krxrdb5553y";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "tortellini" = pkgs.stdenv.mkDerivation {
      name = "tortellini";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/justinwoo/purescript-tortellini.git";
        rev = "v4.0.0";
        sha256 = "0s1sg6fvq9vm0d051llx3hspb2w19nmxhhn1rs7xy6nlarj8ccsz";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "transformers" = pkgs.stdenv.mkDerivation {
      name = "transformers";
      version = "v4.2.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-transformers.git";
        rev = "v4.2.0";
        sha256 = "03qmvl9s7lbvm73dy9ps6qp39pdcm91hb8yakgj7aq8hgpj7b6bg";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "tuples" = pkgs.stdenv.mkDerivation {
      name = "tuples";
      version = "v5.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-tuples.git";
        rev = "v5.1.0";
        sha256 = "045nsy0r2g51gih0wjhcvhl6gfr8947mlrqwg644ygz72rjm8wq4";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "type-equality" = pkgs.stdenv.mkDerivation {
      name = "type-equality";
      version = "v3.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-type-equality.git";
        rev = "v3.0.0";
        sha256 = "1b7szyca5s96gaawvgwrw7fa8r7gqsdff7xhz3vvngnylv2scl3w";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "typelevel-prelude" = pkgs.stdenv.mkDerivation {
      name = "typelevel-prelude";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-typelevel-prelude.git";
        rev = "v4.0.0";
        sha256 = "0j59ibdzbs555pjqmh6v4rampg733kvnicpwmyyrp1xrq8vz9a97";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "unfoldable" = pkgs.stdenv.mkDerivation {
      name = "unfoldable";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-unfoldable.git";
        rev = "v4.0.0";
        sha256 = "077vl30j3pxr3zw6cw7wd0vi22j92j8va15r26rn53wzbzcgr41j";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "unsafe-coerce" = pkgs.stdenv.mkDerivation {
      name = "unsafe-coerce";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-unsafe-coerce.git";
        rev = "v4.0.0";
        sha256 = "0k9255mk2mz6xjb11pwkgfcblmmyvr86ig5kr92jwy95xim09zip";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "unsafe-reference" = pkgs.stdenv.mkDerivation {
      name = "unsafe-reference";
      version = "v3.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-unsafe-reference";
        rev = "v3.0.1";
        sha256 = "0q758dz59qz0li4s3w1qcg921xp5i5rh6i1l611iv7rr8cbj11al";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "validation" = pkgs.stdenv.mkDerivation {
      name = "validation";
      version = "v4.2.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-validation.git";
        rev = "v4.2.0";
        sha256 = "03irk6n7jgsimhp9ckrg2ns7qbc8d383ls3sslxgir5mr8xdc44g";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "variant" = pkgs.stdenv.mkDerivation {
      name = "variant";
      version = "v5.2.0";
      src = pkgs.fetchgit {
        url = "https://github.com/natefaubion/purescript-variant.git";
        rev = "v5.2.0";
        sha256 = "1awxcl3kc3z3hm8kxdg0w74v76pj636nk31d4ggqh49y25v3mpxj";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "web-clipboard" = pkgs.stdenv.mkDerivation {
      name = "web-clipboard";
      version = "v2.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-clipboard.git";
        rev = "v2.0.0";
        sha256 = "17i7rpzxi7pgas32xz8vjcs54m94gnmca3my0p70gzvf3rasnxyx";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "web-dom" = pkgs.stdenv.mkDerivation {
      name = "web-dom";
      version = "v2.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-dom.git";
        rev = "v2.0.0";
        sha256 = "17vcby3mldgzbskp1113krdw9a7z5vc83200685s4sfbf7rhc6w6";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "web-events" = pkgs.stdenv.mkDerivation {
      name = "web-events";
      version = "v2.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-events.git";
        rev = "v2.0.0";
        sha256 = "0z2q9zjjyx3djlkbdhhnhb1aw175rgklb5ylf3rnk9makbfk1rnf";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "web-file" = pkgs.stdenv.mkDerivation {
      name = "web-file";
      version = "v2.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-file.git";
        rev = "v2.0.0";
        sha256 = "05cc4vn1kpn2rzh7b14216v0jidyl7kzfqq7q9ydhmxlwb2k8jix";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "web-html" = pkgs.stdenv.mkDerivation {
      name = "web-html";
      version = "v2.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-html.git";
        rev = "v2.0.0";
        sha256 = "06dvymqxh297zz9h2y07w9hd6p8nw08r79whxjwcyh3zlsjra99d";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "web-storage" = pkgs.stdenv.mkDerivation {
      name = "web-storage";
      version = "v3.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-storage.git";
        rev = "v3.0.0";
        sha256 = "1ycb2s29aw9w6lqik6hfmp9nf9i2yhn0q26hc4p3450jam5mj8bx";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "web-touchevents" = pkgs.stdenv.mkDerivation {
      name = "web-touchevents";
      version = "v2.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-touchevents.git";
        rev = "v2.0.0";
        sha256 = "0mhsfqlglx04q3vkjg4k33bkxcpx2cmbq4x1zxyhl48q1qqmnic8";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "web-uievents" = pkgs.stdenv.mkDerivation {
      name = "web-uievents";
      version = "v2.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-uievents.git";
        rev = "v2.0.0";
        sha256 = "04032nl0z9hjq7b799zhbn7in10dz9kgrrcs0adjbaf08rc2kcwh";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };
};

in {
  inherit inputs;

  set = "psc-0.12.3-20190306";
  source = "https://github.com/purescript/package-sets.git";
}
